#!/bin/sh

set -e

handle_initial_install() {
	true
}

handle_upgrade() {
    # Remove language cache
    rm -f /var/tmp/codendi_cache/lang/*/*.tab
    # Re-generate language files if already configured
    if [ -e /etc/tuleap/conf/local.inc ]; then
	/usr/share/tuleap/src/utils/php-launcher.sh /usr/share/tuleap/src/utils/generate_language_files.php
    fi
}

case "$1" in
    configure)
	if [ -z "$2" ]; then
	    handle_initial_install
	else
	    handle_upgrade
	fi
    ;;
esac

#DEBHELPER#

